version:     "007--14-Nov-2022"
copyright:   "2022"
author:      "Kevin Marcellius Alrino"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/kevinmarcellius/os222/"
myloglink:   "/TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
